# Generated by Django 3.0.6 on 2020-05-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['picture_name']},
        ),
    ]
